name: Build and deploy Python app to Azure Web App - ufc-fight-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for OIDC
      contents: read  # for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6413C953F7BE4996B843279392BC707C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A2788330543742768A0C4E955F73A302 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74FABDBDB3DC4891AD6504CA2D20741D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ufc-fight-backend'
          slot-name: 'Production'
          package: ./backend
